### ISSUE TITLE
rm -r panic

### ISSUE THREAD

**Issue by Prnyself** [yunify/qsctl#135]
I tried to remove all objects from my bucket by rm -r, but got panic:
```
goroutine 1909 [sync.Cond.Wait]:
runtime.goparkunlock(...)
/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0002ea5d0, 0x534)
/usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0002ea5c0)
/usr/local/go/src/sync/cond.go:56 +0x9d
github.com/Xuanwo/navvy.(*Pool).retrieveWorker(0xc00010bf80, 0x1)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/!xuanwo/navvy@v0.0.0-20191010141320-12f3cfcb6a27/pool.go:155 +0x201
github.com/Xuanwo/navvy.(*Pool).Submit(0xc00010bf80, 0x16cc080, 0xc00021a5d0)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/!xuanwo/navvy@v0.0.0-20191010141320-12f3cfcb6a27/pool.go:61 +0x52
created by github.com/yunify/qsctl/v2/utils.SubmitNextTask
/Users/lance/Desktop/QingCloud/projects/modgo/qsctl/utils/utils.go:44 +0x159

goroutine 1908 [sync.Cond.Wait]:
runtime.goparkunlock(...)
/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0002ea5d0, 0x532)
/usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0002ea5c0)
/usr/local/go/src/sync/cond.go:56 +0x9d
github.com/Xuanwo/navvy.(*Pool).retrieveWorker(0xc00010bf80, 0x1)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/!xuanwo/navvy@v0.0.0-20191010141320-12f3cfcb6a27/pool.go:155 +0x201
github.com/Xuanwo/navvy.(*Pool).Submit(0xc00010bf80, 0x16cc1a0, 0xc00021a150)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/!xuanwo/navvy@v0.0.0-20191010141320-12f3cfcb6a27/pool.go:61 +0x52
created by github.com/yunify/qsctl/v2/utils.SubmitNextTask
/Users/lance/Desktop/QingCloud/projects/modgo/qsctl/utils/utils.go:44 +0x159

goroutine 1279 [IO wait]:
internal/poll.runtime_pollWait(0x1f5a158, 0x72, 0xffffffffffffffff)
/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0007c1218, 0x72, 0xf00, 0xf3d, 0xffffffffffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0007c1200, 0xc0009b6000, 0xf3d, 0xf3d, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x22b
net.(*netFD).Read(0xc0007c1200, 0xc0009b6000, 0xf3d, 0xf3d, 0x1a92e40, 0xe9, 0x0)
/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010090, 0xc0009b6000, 0xf3d, 0xf3d, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:184 +0x68
github.com/yunify/qingstor-sdk-go/v3/utils.Conn.Read(0x4f07240, 0xc000010090, 0x6fc23ac00, 0x6fc23ac00, 0x0, 0xc0009b6000, 0xf3d, 0xf3d, 0x203000, 0x203000, ...)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/yunify/qingstor-sdk-go/v3@v3.1.2-0.20191015085047-089474e57bf8/utils/conn.go:91 +0x68
crypto/tls.(*atLeastReader).Read(0xc0001980e0, 0xc0009b6000, 0xf3d, 0xf3d, 0x0, 0x0, 0xc0006248a0)
/usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc0006b2258, 0x16cb800, 0xc0001980e0, 0x100b855, 0x1571dc0, 0x15c2740)
/usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc0006b2000, 0x4f07298, 0xc0008708a0, 0x5, 0xc0008708a0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc0006b2000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc0006b2000, 0xc000568000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:1255 +0x161
net/http.(*persistConn).Read(0xc0002326c0, 0xc000568000, 0x1000, 0x1000, 0x10067ad, 0x60, 0x0)
/usr/local/go/src/net/http/transport.go:1744 +0x75
bufio.(*Reader).fill(0xc0008204e0)
/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0008204e0, 0x1, 0xc000102ea0, 0x0, 0x1386c79, 0xc0005a8c98, 0x1048757)
/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0002326c0)
/usr/local/go/src/net/http/transport.go:1897 +0x1d6
created by net/http.(*Transport).dialConn
/usr/local/go/src/net/http/transport.go:1566 +0xafe

goroutine 1299 [select]:
net.(*Resolver).lookupIPAddr(0x1a92660, 0x16d7880, 0xc0009361e0, 0x16062df, 0x3, 0xc0001b0c20, 0x12, 0x1bb, 0x0, 0x0, ...)
/usr/local/go/src/net/lookup.go:275 +0x664
net.(*Resolver).internetAddrList(0x1a92660, 0x16d7880, 0xc0009361e0, 0x16062df, 0x3, 0xc0001b0c20, 0x16, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/net/ipsock.go:280 +0x605
net.(*Resolver).resolveAddrList(0x1a92660, 0x16d7880, 0xc0009361e0, 0x16065d9, 0x4, 0x16062df, 0x3, 0xc0001b0c20, 0x16, 0x0, ...)
/usr/local/go/src/net/dial.go:220 +0x506
net.(*Dialer).DialContext(0xc000127c20, 0x16d7840, 0xc0000ae008, 0x16062df, 0x3, 0xc0001b0c20, 0x16, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/net/dial.go:402 +0x1fe
github.com/yunify/qingstor-sdk-go/v3/utils.(*Dialer).DialContext(0xc0002becc0, 0x16d7840, 0xc0000ae008, 0x16062df, 0x3, 0xc0001b0c20, 0x16, 0xc00054c480, 0x118, 0x118, ...)
/users/lance/desktop/qingcloud/projects/go/pkg/mod/github.com/yunify/qingstor-sdk-go/v3@v3.1.2-0.20191015085047-089474e57bf8/utils/conn.go:47 +0x80
net/http.(*Transport).dial(0xc0002cab40, 0x16d7840, 0xc0000ae008, 0x16062df, 0x3, 0xc0001b0c20, 0x16, 0x0, 0x1326ff0, 0xc0003f1c00, ...)
/usr/local/go/src/net/http/transport.go:1034 +0x1f5
net/http.(*Transport).dialConn(0xc0002cab40, 0x16d7840, 0xc0000ae008, 0x0, 0xc00054c180, 0x5, 0xc0001b0c20, 0x16, 0x0, 0x16314d0, ...)
/usr/local/go/src/net/http/transport.go:1470 +0x193e
net/http.(*Transport).dialConnFor(0xc0002cab40, 0xc00050ee70)
/usr/local/go/src/net/http/transport.go:1300 +0xdc
created by net/http.(*Transport).queueForDial
/usr/local/go/src/net/http/transport.go:1269 +0x41d
```

**Comment by Xuanwo** [comment]
Should be fixed in task system refactor.
