### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by wangzw** [yunify/qsctl#15]
```
[root@i-0ygo7ve6 x86_64]# qsctl ls qs://hashdata-public
[2017-01-20 15:14:26,615] qingstor-sdk parse DEBUG:
parsed_uri: https://qingstor.com:443/
[2017-01-20 15:14:26,616] qingstor-sdk get_authorization DEBUG:
GET

application/octet-stream
Fri, 20 Jan 2017 07:14:26 GMT
/
[2017-01-20 15:14:27,421] qingstor-sdk __init__ DEBUG:
status_code: 200
[2017-01-20 15:14:27,421] qingstor-sdk unpack_response_body DEBUG:
count: 2
[2017-01-20 15:14:27,422] qingstor-sdk unpack_response_body DEBUG:
buckets: [{u'url': u'http://hashdata-public.pek3a.qingstor.com', u'location': u'pek3a', u'name': u'hashdata-public', u'created': u'2016-04-12T03:26:47Z'}, {u'url': u'http://hashdata-test.pek3a.qingstor.com', u'location': u'pek3a', u'name': u'hashdata-test', u'created': u'2016-06-01T09:33:44Z'}]
[2017-01-20 15:14:27,422] qingstor-sdk parse DEBUG:
parsed_uri: https://pek3a.qingstor.com:443/hashdata-public
[2017-01-20 15:14:27,422] qingstor-sdk get_authorization DEBUG:
HEAD

application/octet-stream
Fri, 20 Jan 2017 07:14:27 GMT
/hashdata-public
[2017-01-20 15:14:27,540] qingstor-sdk __init__ DEBUG:
status_code: 200
Traceback (most recent call last):
  File "/usr/bin/qsctl", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/qsctl", line 23, in main
    return qingstor.qsctl.driver.main()
  File "/usr/lib/python2.7/site-packages/qingstor/qsctl/driver.py", line 91, in main
    command.main(args[2:])
  File "/usr/lib/python2.7/site-packages/qingstor/qsctl/commands/base.py", line 225, in main
    return cls.send_request(options)
  File "/usr/lib/python2.7/site-packages/qingstor/qsctl/commands/ls.py", line 128, in send_request
    cls.list_keys(options)
  File "/usr/lib/python2.7/site-packages/qingstor/qsctl/commands/ls.py", line 117, in list_keys
    bucket, prefix, delimiter, marker, limit
  File "/usr/lib/python2.7/site-packages/qingstor/qsctl/commands/base.py", line 202, in list_multiple_keys
    marker=marker, prefix=prefix, delimiter=delimiter, limit=limit
  File "/usr/lib/python2.7/site-packages/qingstor/sdk/service/bucket.py", line 364, in list_objects
    delimiter=delimiter, limit=limit, marker=marker, prefix=prefix
  File "/usr/lib/python2.7/site-packages/qingstor/sdk/service/bucket.py", line 360, in list_objects_request
    return Request(self.config, operation)
  File "/usr/lib/python2.7/site-packages/qingstor/sdk/request.py", line 34, in __init__
    self.req = Builder(config, operation).parse()
  File "/usr/lib/python2.7/site-packages/qingstor/sdk/build.py", line 49, in parse
    parsed_operation["URI"] = self.parse_request_uri()
  File "/usr/lib/python2.7/site-packages/qingstor/sdk/build.py", line 171, in parse_request_uri
    params_parts.append("%s=%s" % (k, quote(v.encode("utf-8"))))
AttributeError: 'int' object has no attribute 'encode'
[root@i-0ygo7ve6 x86_64]# pip freeze | grep qing
qingstor-sdk==2.0.2
[root@i-0ygo7ve6 x86_64]# pip freeze | grep qs
qsctl==1.2.1
```

**Comment by Xuanwo** [comment]
Related to https://github.com/yunify/qsctl/pull/14 ,i'm working on it, sorry for waiting.

**Comment by Xuanwo** [comment]
Closed for https://github.com/yunify/qsctl/pull/14 merged, please reopen if this bug is still existing.

And thank you for reporting.
