### ISSUE TITLE
failed use cp command on Ubuntu Server 18.04.1 LTS 64bit

### ISSUE THREAD

**Issue by markduan** [yunify/qsctl#174]
debug log

```
❯ qsctl cp Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4 qs://mark-movie
DEBU[2019-11-08T17:45:47+08:00] Started CopyFileTask {DestinationPath: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, DestinationStorage: qingstor Storager {WorkDir /}, SourcePath: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, SourceStorage: posixfs Storager {WorkDir /mnt/plex/Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG}}
DEBU[2019-11-08T17:45:47+08:00] Started CopyLargeFileTask {DestinationPath: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, DestinationStorage: qingstor Storager {WorkDir /}, SourcePath: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, SourceStorage: posixfs Storager {WorkDir /mnt/plex/Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG}, TotalSize: 2185046542}
DEBU[2019-11-08T17:45:47+08:00] Started SegmentInitTask {PartSize: 134217728, Path: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, Storage: qingstor Storager {WorkDir /}}
DEBU[2019-11-08T17:45:47+08:00] Finished SegmentInitTask {PartSize: 134217728, Path: Death.Wish.2018.1080p.BluRay.H264.AAC-RARBG.mp4, Storage: qingstor Storager {WorkDir /}}
panic: SegmentID value is not valid

goroutine 14 [running]:
github.com/yunify/qsctl/v2/pkg/types.(*SegmentID).GetSegmentID(0xc0001c51b8, 0x0, 0x0)
        github.com/yunify/qsctl/v2@/pkg/types/types.go:2039 +0xea
github.com/yunify/qsctl/v2/task.(*CopyLargeFileTask).run(0xc000092000)
        github.com/yunify/qsctl/v2@/task/copy.go:71 +0x18c
github.com/yunify/qsctl/v2/task.(*CopyLargeFileTask).Run(0xc000092000)
        github.com/yunify/qsctl/v2@/task/generated.go:251 +0xa4
github.com/yunify/qsctl/v2/pkg/schedule.(*task).Run(0xc000486100)
        github.com/yunify/qsctl/v2@/pkg/schedule/scheduler.go:63 +0x64
created by github.com/yunify/qsctl/v2/pkg/schedule.(*RealScheduler).Sync
        github.com/yunify/qsctl/v2@/pkg/schedule/scheduler.go:86 +0xff
```

**Comment by Xuanwo** [comment]
Fixed in https://github.com/yunify/qsctl/pull/177

**Comment by Xuanwo** [comment]
#177 merged.
