### ISSUE TITLE
error when uploading artifacts: No module named concurrent.futures 

### ISSUE THREAD

**Issue by martinyunify** [yunify/qsctl#56]
I got this error when uploading files to bucket 
Traceback (most recent call last):
  File "/usr/local/bin/qsctl", line 21, in <module>
    import qingstor.qsctl.driver
  File "/usr/local/lib/python2.7/dist-packages/qingstor/qsctl/driver.py", line 28, in <module>
    from qingstor.qsctl.commands.ls import LsCommand
  File "/usr/local/lib/python2.7/dist-packages/qingstor/qsctl/commands/ls.py", line 23, in <module>
    from .base import BaseCommand
  File "/usr/local/lib/python2.7/dist-packages/qingstor/qsctl/commands/base.py", line 25, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures

Full build log can be found here : https://travis-ci.org/QingCloudAppcenter/user-guide/builds/276486639

**Comment by martinyunify** [comment]
I think it would be helpful if cron build of travis service is enabled.
